### ISSUE TITLE
test failure in ORBoost and SVORIM

### ISSUE THREAD

**Issue by durka** [ayrna/orca#44]
After making a few edits to get the toolbox compiling on macOS (see #45), I got these errors when running `runtestssingle`:

### ORBoost

```
Index exceeds matrix dimensions.

Error in ORBoost/privpredict (line 123)
            predicted = all(:,1);

Error in Algorithm/predict (line 80)
            [projected, predicted]= privpredict(obj,test);

Error in ORBoost/privfit (line 84)
            [projectedTrain,predictedTrain] = obj.predict(train.patterns);

Error in Algorithm/fit (line 65)
            [projectedTrain, predictedTrain] = obj.privfit(train, param);

Error in Algorithm/runAlgorithm (line 33)
            [mInf.projectedTrain, mInf.predictedTrain] = obj.fit(train,param);

Error in orboostTest (line 13)
info = algorithmObj.runAlgorithm(train,test);

Error in runtestssingle (line 37)
        eval(cmd(1:end-2))
```

### SVORIM

```
Error using svorimTest (line 35)
Test accuracy does NOT match reference accuracy

Error in runtestssingle (line 37)
        eval(cmd(1:end-2))
```

**Comment by javism** [comment]
Dear Durka, 
Sorry, we haven't tested the framework in Mac.

The **SVORIM** failure is a problem with reference accuracy. We have seen differences in performance among OS and compiler versions. I think we should raise a warning instead of an error in the testing code and only launch an error if the fit/predict methods fails. @pagutierrez 

Regarding **ORboost**, please, check that you correctly build the code. I have to say that the Orboost code is old-C code difficult to update. We were thinking in removing this method from the standard code.

**Comment by javism** [comment]
We finally managed somebody with Mac to try the code, it seems that ORboost only works with GNU compiler. Please, try that.
