### ISSUE TITLE
[bug] In DataSet.standarizeData

### ISSUE THREAD

**Issue by doctormee** [ayrna/orca#63]
in DataSet.standarizeFunction (line 106)` XStds = std(X)` operates across **columns**, not **rows**.

Example:
    `>> X = [1 2 3; 4 5 6]`

X =

     1     2     3
     4     5     6

`>> std(X)`

ans =

    2.1213    2.1213    2.1213`

matlab version: 9.6.0.1072779 (R2019a)

Suggested solution: change line 106 to `XStds = std(X.')`

**Comment by javism** [comment]
Hi @doctormee, 

I think you have these results because you are using the std funcion of matlab/octave. std return the standard deviation of columns or rows. 

If you want to standarize data, 0 mean and 1 standard deviation for each variable, you have to do the following: 

```matlab
octave:1> addpath src/Utils/
octave:2> X = [1 2 3; 4 5 6]
X =

   1   2   3
   4   5   6

octave:3> DataSet.standarizeFunction(X)
ans =

  -0.70711  -0.70711  -0.70711
   0.70711   0.70711   0.70711
```
`DataSet.standarizeFunction` assumes the data is organizes in one row per patern, so each column represents a variable.
