### ISSUE TITLE
Handling folds execution failure

### ISSUE THREAD

**Issue by javism** [ayrna/orca#8]
If a methods fails to end a fold experiment (example fold 15), the results table is build without any notification to the user.

The second issue, is that in the report file the folds rows are secuentially numbered, so that if fold 15 fails,  'dataset/results_test.csv', it still appearing (ex. test_dermatology.15) , and last identifier of experiment is suppressed (test_dermatology.9).

**Comment by zhutuanfei** [comment]
hello, javism, there are some problems when i use orca-master in matlab. I tried to compile  libsvm-rank-2.81, SVOREX and SVORIM  by running their corresponding "make.m", but all of them failed(my matlab's version is 2013b, and the compiler is "Microsoft Visual Studio 10.0" ). 

For libsvm-rank-2.81, many errors occurred in the process of compiling "svmpredict.c". All of them are  syntax errors, e.g., missing ":" or undeclared identifiers.

For SVOREX, the error message is listed below:
" C:\PROGRA~1\MATLAB\R2013B\BIN\MEX.PL: Error: Unrecognized switch: -o.  
Unable to complete successfully.
Error in make (line 3)
	mex CFLAGS="\$CFLAGS -std=c99" -largeArrayDims mainSvorex.c alphas.c
    cachelist.c datalist.c def_settings.c kcv.c loadfile.c
    ordinal_takestep.c setandfi.c smo_kernel.c smo_routine.c smo_settings.c
    sm
Error in run (line 63)
evalin('caller', [script ';']);
"

For SVORIM, the error message is described  below:
"C:\PROGRA~1\MATLAB\R2013B\BIN\MEX.PL: Error: Unrecognized switch: -o.  
Unable to complete successfully.
Error in make (line 3)
	mex CFLAGS="\$CFLAGS -std=c99 -O3 -fPIC" -largeArrayDims mainSvorim.c
    alphas.c cachelist.c datalist.c def_settings.c kcv.c loadfile.c
    ordinal_takestep.c setandfi.c smo_kernel.c smo_routine.c smo_set
Error in run (line 63)
evalin('caller', [script ';']);
"

I want to know what causes these problems and how to solve them? Looking forward to your reply. Thank you for your attention.

**Comment by pagutierrez** [comment]
Hi zhutuanfei:
For the problem with libsvm-rank, please send us the errors.
For the problem with SVOREX, change the corresponding make.m (SVOREX/make.m) by replacing the "-o" option of mex by "-output". There have been a change in the parameter names of mex.
Many thanks for your interest,
Pedro

**Comment by zhutuanfei** [comment]
@pagutierrez
hi pagutierrez, i have another problem when SVOREX and SVORIM are running. The errors are shown as follows:

Error using distcomp.remoteparfor/getCompleteIntervals (line 22)
The session that parfor is using has shut down.

Caused by:
Error using distcomp.remoteparfor/getCompleteIntervals (line 22)
The session that parfor is using has shut down.

The client lost connection to lab 12. This might be due to network problems, or
the interactive matlabpool job might have errored.

do you have any suggestion to fix this problem? thanks a lot.

**Comment by zhutuanfei** [comment]
@pagutierrez
I have no idea to solve the issue that SVOREX and SVORIM cannot be run successfully. As POM and ELMOP have been running fine, i  doubt  that the issue may be caused by the incorrect compilations for SVOREX and SVORIM. Could you provide your compiled mex files for me? my matlab version is 2009a with 64bit. Looking forward to your reply. Thank you for your attention.

ps: when Parallel computing disable, i.e., to call "Utilities.runExperiments(['config-files/' d(1).name], false) with SVOREX as base learner", after processing some dataset,  matlab will be forced to  stop and then disappeared without any warning.

**Comment by zhutuanfei** [comment]
@pagutierrez
supplement：
**hi pagutierrez,   i found the reason why SVOREX and SVORIM cannot be run successfully, that is because the KKT conditions are violated. From "smo_routine.c" file, if KKT conditions are violated, the program will exit. The related source code  is listed below:**
"
_if (settings->bmu_low[loop-1] - settings->bmu_up[loop-1]>TOL)
		{
			printf("Warning: KKT conditions are violated on bias!!! %f with C=%.3f K=%.3f\r\n",
				settings->bmu_low[loop-1] + settings->bmu_up[loop-1], VC, KAPPA) ;
			        exit(1) ;
		}_

could you offer any suggestion to me for this issue?  thanks a lot.

**Comment by pagutierrez** [comment]
Hi @zhutuanfei 
Is your data correct? All labels has to be consecutive numbers, starting with 1, 1, 2, 3... Is it possible for you to send me the data so I can analyze it?

**Comment by zhutuanfei** [comment]
@pagutierrez
thank you for your reply. 

All data sets to run the experiment are provided by your lab, which i download from the websites "http://www.uco.es/grupos/ayrna/orreview" and " http://www.uco.es/grupos/ayrna/GBOforOR". 
Hence, i thank these data sets should not be a problem themselves. But each of them are preprocessed   before feeding them into training, i.e., oversampling all minority classes to reach a more balanced class distribution.  According to your suggestion,  may be  the labels of synthetic samples result in the problem? 

ps: I commented the code line of "exit(1)"  and then recompiled all of  the source code. Although this is very cursory, it  can work(at least until now).

**Comment by pagutierrez** [comment]
I think you should try to run the code using the datasets without preprocessing, to see if the problem is related with the oversampling process you have applied. Commenting the line of course can avoid the problem, but I would be a bit skeptical about the results. It seems you are having unordered biases, which is very strange...

**Comment by zhutuanfei** [comment]
@pagutierrez

Thanks for your advice!

For the reliability of  the results,  i think that the weird model with unordered biases mainly impacts the result of optimal  parameters, because most of the trained models are used to find the optimal C and kernel paramter(i.e., cross  validation),

If the label values of original data are consecutive, it is not possible that the labels of oversampled data are not consecutive ( i just add the new synthetic samples into original data and do not remove any original samples). In fact, i did find a case that the labels of training data are consecutive but the KKT conditions of the model  are violated.

**Comment by javism** [comment]
Dear @zhutuanfei, we have ported ORCA to Windows platforms. Please, follow install instructions in https://github.com/ayrna/orca/blob/master/doc/orca-install.md
